# SQLite-backed shared secret / user database
# See: https://github.com/coturn/coturn/blob/master/docs/SQLite.md
# and: https://github.com/coturn/coturn/blob/master/examples/scripts/restapi/secure_relay_secret_with_db_sqlite.sh
# SQLite database for long-term creds and shared-secret tables
# Example: /var/lib/turn/turndb or /var/db/turndb
# Create it with: sqlite3 /var/lib/turn/turndb < turndb/schema.sql

use-auth-secret
realm=computertalkrnd.com
userdb=/var/lib/turn/turndb
sock-buf-size=1048576
dtls
server-name=rndcoturn.computertalkrnd.com
listening-ip=10.0.150.30
relay-ip=10.0.150.30
listening-port=3478
tls-listening-port=5349
min-port=10000
max-port=20000
no-loopback-peers
no-multicast-peers
no-cli
fingerprint
cert=/etc/kamailio/tls/computertalkrnd.com_cert.pem
pkey=/etc/kamailio/tls/computertalkrnd.com_key.pem
log-file=stdout
udp-recvmmsg
